// v0.2-alpha-16 — ChatView (Preact JSX).
//
// Renders the message list + the active streaming bubble + transient
// errors + the welcome screen into the existing `<div id="messages">`
// shell defined in index.html. The component subscribes to chatStore
// for state; main.ts drives the store via the mutators in
// chat-view-store.ts.
//
// What lives here vs. what stays in main.ts:
//   - HERE:  message bubble rendering, streaming bubble rendering,
//            welcome screen, error bubble, auto-scroll-to-bottom.
//   - MAIN:  input form (textarea + send button + char count +
//            attachment previews + mic/attach buttons + drag-drop +
//            Enter to submit) — it stays in main.ts because it's
//            tightly coupled to the SSE submit pipeline (handleSubmit
//            → createSession → addMessage → sendMessage). alpha-17
//            will lift this once the streaming submit is also
//            migrated to a Preact-friendly path.

import { useEffect, useRef, useState } from "preact/hooks";
import {
  chatStore,
  formatMessage,
  type ChatMessage,
  type ChatMessageBar,
  type PendingAttachment,
} from "./chat-view-store";
import type { ChatStoreState } from "./chat-view-store";

interface WelcomeContext {
  /** Override the headline emoji + text (default: "👋 欢迎使用 Hermes Chat"). */
  headline?: string;
  /** Persona badge line (when set). */
  persona?: { avatar: string; name: string } | null;
  /** Project hint line (when set). scanFailed shows a different label. */
  project?: { name: string; version?: string; path?: string; scanFailed?: boolean } | null;
}

function WelcomeBubble({ context }: { context: WelcomeContext | null }) {
  const headline = context?.headline ?? "👋 欢迎使用 Hermes Chat";
  const persona = context?.persona;
  const project = context?.project;
  const hintLines: string[] = [];
  if (persona) {
    hintLines.push(`Persona: ${persona.avatar ?? ""} ${persona.name}`);
  }
  if (project) {
    if (project.scanFailed) {
      hintLines.push(`项目路径已设置但扫描失败: ${project.path ?? ""}`);
    } else {
      const ver = project.version ? ` v${project.version}` : "";
      const path = project.path ? ` (${project.path})` : "";
      hintLines.push(`项目: ${project.name}${ver}${path}`);
    }
  }
  if (hintLines.length === 0) {
    hintLines.push("在下方输入消息开始对话");
  }
  return (
    <div class="welcome-message">
      <p>{headline}</p>
      {hintLines.map((line, i) => (
        <p key={i} class="hint">{line}</p>
      ))}
    </div>
  );
}

function UserBubble({ msg }: { msg: ChatMessage }) {
  // User messages render attachments as a thumbnail strip + the raw
  // text below. We DO NOT markdown-render user content — that would be
  // an XSS vector if the model ever echoes user input back to another
  // user. main.ts guarantees user text comes from a trusted textarea.
  return (
    <div class="message user">
      <div class="message-avatar">👤</div>
      <div class="message-content">{msg.content}</div>
      {msg.attachments && msg.attachments.length > 0 ? (
        <AttachmentStrip attachments={msg.attachments} />
      ) : null}
    </div>
  );
}

function AssistantBubble({ msg }: { msg: ChatMessage }) {
  return (
    <div class="message assistant">
      <div class="message-avatar">🤖</div>
      <div
        class="message-content"
        // marked.parse returns sanitised GFM HTML. Assistant content is
        // generated by the agent (a trusted side) but still rendered
        // as innerHTML — see AGENTS.md §security for the threat model.
        dangerouslySetInnerHTML={{ __html: formatMessage(msg.content) }}
      />
      {msg.bar ? <MessageBar bar={msg.bar} /> : null}
    </div>
  );
}

function StreamingBubble({ content }: { content: string }) {
  // We render the streaming bubble with the same shape as a finalised
  // assistant bubble so the user's eye doesn't jump when the stream
  // finalises. The "is-streaming" class is purely cosmetic (CSS can
  // show a subtle pulse if desired) — semantics don't depend on it.
  return (
    <div class="message assistant is-streaming">
      <div class="message-avatar">🤖</div>
      <div
        class="message-content"
        dangerouslySetInnerHTML={{ __html: formatMessage(content) }}
      />
    </div>
  );
}

function ErrorBubble({ message }: { message: string }) {
  // We render the gateway URL inline so the user can see the address
  // the tray was trying to reach — matches the v0.1.5 message verbatim
  // for visual regression parity.
  // We can't easily get the URL into JSX without lifting it through
  // the store, so we keep the existing message format and just embed
  // the human-readable part. main.ts continues to log the full URL.
  return (
    <div class="message error">
      <div class="message-content">
        ❌ {message}
      </div>
    </div>
  );
}

function AttachmentStrip({ attachments }: { attachments: PendingAttachment[] }) {
  return (
    <div class="message-attachments">
      {attachments.map((a, idx) => (
        // Fall back to the array index when no id is present (older
        // attachments without crypto.randomUUID). Stable enough since
        // user bubbles rarely re-render in place.
        <div key={a.id ?? `att-${idx}`} class="message-attachment">
          {a.type.startsWith("image/") ? (
            <img src={a.dataUrl} alt={a.name} class="message-attachment-thumb" />
          ) : (
            <div class="message-attachment-file">📎 {a.name}</div>
          )}
        </div>
      ))}
    </div>
  );
}

function MessageBar({ bar }: { bar: ChatMessageBar }) {
  const className = bar.costThresholdExceeded ? "message-bar message-bar-warn" : "message-bar";
  // formatMessageBar is a pure function — imported for parity with
  // the inline formatters in src/lib/chat-formatters.ts. We render
  // the bar text content directly (no HTML interpolation needed).
  const text = renderBarText(bar);
  if (!text) return null;
  return <div class={className}>{text}</div>;
}

/**
 * Local copy of formatMessageBar to keep the Preact component free of
 * direct DOM-builder imports. The DOM-builder version lives in
 * chat-formatters.ts for the imperative call site in finishStream.
 */
function renderBarText(bar: ChatMessageBar): string | null {
  const parts: string[] = [];
  if (bar.costUsd > 0) parts.push(`💰 $${bar.costUsd.toFixed(4)}`);
  if (bar.elapsedMs != null && bar.elapsedMs > 0) {
    const ms = bar.elapsedMs;
    const latency = ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(1)}s`;
    parts.push(`⏱ ${latency}`);
  }
  if (bar.ruleId) {
    parts.push(`🛡 ${bar.ruleId}`);
  } else if (bar.costThresholdExceeded) {
    parts.push("🛡 cost_threshold_exceeded");
  }
  if (parts.length === 0) return null;
  return parts.join(" · ");
}

export function ChatView({ welcomeContext }: { welcomeContext?: WelcomeContext | null }) {
  const [state, setState] = useState<ChatStoreState>(chatStore.get());
  const scrollRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => chatStore.subscribe(setState), []);

  // Auto-scroll to bottom on every state change. We don't compare to
  // previous state — Preact bails out re-renders when the store
  // reference is unchanged, so we only land here when something
  // actually changed. The user's manual scroll-up is preserved
  // between renders because we only scroll the container itself.
  useEffect(() => {
    const el = scrollRef.current?.parentElement;
    if (el) el.scrollTop = el.scrollHeight;
  }, [state]);

  const showWelcome =
    state.messages.length === 0 && state.streaming === null && state.error === null;

  return (
    <div ref={scrollRef} class="chat-view">
      {state.messages.map((m) =>
        m.role === "user" ? (
          <UserBubble key={messageKey(m)} msg={m} />
        ) : (
          <AssistantBubble key={messageKey(m)} msg={m} />
        ),
      )}
      {state.streaming ? <StreamingBubble content={state.streaming.content} /> : null}
      {state.error ? <ErrorBubble message={state.error} /> : null}
      {showWelcome ? <WelcomeBubble context={welcomeContext ?? null} /> : null}
    </div>
  );
}

/**
 * Stable key per message. We use `timestamp.getTime()` cast to string
 * since ChatMessage doesn't carry an explicit id field (we add one
 * lazily in the store when finalising a stream).
 *
 * If a message has no timestamp yet (shouldn't happen — every path
 * sets one), fall back to its position so we still get a valid key.
 */
function messageKey(m: ChatMessage & { id?: string }): string {
  if (m.id) return m.id;
  return m.timestamp ? `t-${m.timestamp.getTime()}` : `i-${Math.random()}`;
}

/* ── Welcome context store ──────────────────────────────────────────────── */

interface WelcomeStore {
  context: WelcomeContext | null;
}

const welcomeListeners = new Set<(s: WelcomeStore) => void>();
let welcomeState: WelcomeStore = { context: null };

function notifyWelcome(): void {
  for (const l of welcomeListeners) l(welcomeState);
}

export const chatWelcomeStore = {
  get(): WelcomeStore {
    return welcomeState;
  },
  setContext(context: WelcomeContext | null): void {
    welcomeState = { context };
    notifyWelcome();
  },
  subscribe(listener: (s: WelcomeStore) => void): () => void {
    welcomeListeners.add(listener);
    listener(welcomeState);
    return () => {
      welcomeListeners.delete(listener);
    };
  },
};

/**
 * ChatViewWithWelcome — convenience wrapper that subscribes to
 * `chatWelcomeStore` and passes the latest context into <ChatView>.
 * main.ts renders this single component; the input form + sidebar +
 * header all stay outside the Preact tree for now (alpha-17 scope).
 */
export function ChatViewWithWelcome() {
  const [welcome, setWelcome] = useState<WelcomeStore>(chatWelcomeStore.get());
  useEffect(() => chatWelcomeStore.subscribe(setWelcome), []);
  return <ChatView welcomeContext={welcome.context} />;
}